### ISSUE TITLE
Tests TODO

### ISSUE THREAD

**Issue by XhmikosR** [MaxCDN/bootstrapcdn#1134]
* [x] `curl ifconfig.co` before tests to get the machine's IP
* [x] Run our tests one time with `Pragma: debug` and one without; we shouldn't see `Debug: Enabled` nor `X-HW` headers without Debug
    * [x] With `Pragma: debug`
    * [x] Without `Pragma: debug`
* [ ] run our tests for all POPs (pending IPs) or maybe for 10 random ones?
* [ ] run tests for both lowercase `accept-encoding` and camelcase
* [x] review if our list of compressible files is right and add/remove any ones
* [x] review our content-types for fonts and js

**Comment by XhmikosR** [comment]
Also

* `curl ifconfig.co` before tests to get the machine's IP
* run our tests for all POPs (pending IPs)

**Comment by XhmikosR** [comment]
Eventually, we need to review if our list of compressible files is right and add/remove any ones

Also, we should review our content-types for fonts and js.
